project:
  type: website

website:
  title: "music-dashboard"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: dashboard.qmd
              Dashboard

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



